version: "3.8"

# Docker Stack configuration for production
# This file is used for deploying to a Docker Swarm cluster

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-rbitly}
      POSTGRES_DB: ${POSTGRES_DB:-rbitly}
      # POSTGRES_PASSWORD is provided via environment variables or secrets
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata_stack:/var/lib/postgresql/data
    networks:
      - rbitly-internal
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
      restart_policy:
        condition: on-failure

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata_stack:/data
    networks:
      - rbitly-internal
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.25"
      restart_policy:
        condition: on-failure

  app:
    # Image will be pulled from GHCR
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-rojanmagar2001}/rbitly:latest
    networks:
      - rbitly-internal
      - rbitly-public
    environment:
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      IP_HASH_SALT: ${IP_HASH_SALT}
      COOKIE_SECRET: ${COOKIE_SECRET}
      METRICS_TOKEN: ${METRICS_TOKEN}
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G
          cpus: "0.5"

networks:
  rbitly-internal:
    driver: overlay
    attachable: true
  rbitly-public:
    driver: overlay
    attachable: true

volumes:
  pgdata_stack:
    driver: local
  redisdata_stack:
    driver: local
